#Code with the topic : Design Matrix

#Description:

#A data table organized in the form of a numerical matrix, where each row represents an observation and each column a variable, prepared to be used in mathematical calculations in machine learning models.

#Technologies used:

#Python
#Numpy
#Pandas
#Visual Code Studio 

#How we have to use the code ?

#We will use this code to understand the structure and how the Matrux design works


In [26]:
#We import the libraries we are going to use
import pandas as pd
import numpy as np

In [27]:
#We have it read the file to process it and then use it
datos = pd.read_csv("Design_matrix.csv")

In [28]:
#We see the data in tables.
datos.head()

,Edad,Salario,Compro
0,20,2000,0
1,25,1600,1
2,30,2100,1


In [29]:
datos.describe()

,Edad,Salario,Compro
count,3.0,3.000000,3.000000
mean,25.0,1900.000000,0.666667
std,5.0,264.575131,0.577350
min,20.0,1600.000000,0.000000
25%,22.5,1800.000000,0.500000
50%,25.0,2000.000000,1.000000
75%,27.5,2050.000000,1.000000
max,30.0,2100.000000,1.000000


In [30]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Edad     3 non-null      int64
 1   Salario  3 non-null      int64
 2   Compro   3 non-null      int64
dtypes: int64(3)
memory usage: 204.0 bytes


In [31]:
#We use columns to avoid mistakes when writing variables when defining X and Y.
datos.columns

Index(['Edad', 'Salario', 'Compro'], dtype='object')

In [32]:
#Separar X (características) e y (objetivo)
X = datos[["Edad","Salario"]]
Y = datos["Compro"]

In [33]:
#We converted to Numoy
X = X.values

In [34]:
# # Add column of 1s (bias that is ones)
ones = np.ones((X.shape[0], 1))
design_matrix = np.hstack((ones, X))

print(design_matrix)

[[1.0e+00 2.0e+01 2.0e+03]
 [1.0e+00 2.5e+01 1.6e+03]
 [1.0e+00 3.0e+01 2.1e+03]]


In [35]:
#What does the result mean ?

#It is interpreted in this way: NumPy converts the data into matrices or "tables".

#This is how it's interpreted:

#First column → bias (intercept)
#Second column → age
#Third column → salary